project:
  type: website

website:
  title: "ISSS626-Geospatial Analytics and Applications"
  navbar:
    left:
    - text: "Hands-on Exercise"
      menu: 
        - text: "Hands-on Exercise 1 - Part 1"
          href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
        - text: "Hands-on Exercise 1 - Part 2"
          href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01part2.html"
        - text: "Hands-on Exercise 2 - Part 1 "
          href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html"
        - text: "Hands-on Exercise 2 - Part 2 "
          href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02_Part2.html"
        - text: "Hands-on Exercise 3  "
          href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03.html"
        - text: "Hands-on Exercise 4  "
          href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04.html"          
    - text: "In-class Exercise"
      menu:
        - text: "In-class Exercise 1"
          href: "In-class-Ex/In-class_Ex01/In-class-Ex01.html"
        - text: "In-class Exercise 2"
          href: "In-class-Ex/In-class_Ex02/In-class_Ex02.html"
        - text: "In-class Exercise 3"
          href: "In-class-Ex/In-class_Ex03/In-class_Ex03.html"
        - text: "In-class Exercise 4"
          href: "In-class-Ex/In-class_Ex04/In-class_Ex04.html"
    - text: "Take-home Exercise"
      menu: 
        - text: "Take-home Exercise 1"
          href: "Take-home_Ex/Take-home_Ex01/Take-home_Ex01.html"
    listing:


format: 
  html: 
    theme: darkly
    css: dark-tech.css
    toc: true
    
editor: visual
