project:
  type: website

website:
  title: "ISSS626-Geospatial Analytics and Applications"
  navbar:
    left:
    - text: "Hands-on Exercise"
      menu: 
        - text: "Hands-on Exercise 1 - Part 1"
          href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
        - text: "Hands-on Exercise 1 - Part 2"
          href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01part2.html"
    - text: "In-class Exercise"
      menu:
        - text: "In-class Exercise 1"
          href: "In-class-Ex/In-class_Ex01/In-class-Ex01.html"
    right:
    - href: index.qmd
      text: "Home"

format: 
  html: 
    theme: darkly
    css: dark-tech.css
    toc: true
    
editor: visual
