---
title: "In-class_Ex03"
author: "Luo Yuming"
date: "Sep 9 2024"
date-modified: "last-modified"
execute: 
  eval: true
  echo: true
  message: false
  freeze: true
---

------------------------------------------------------------------------
```{r}
pacman::p_load(sf, spNetwork, tmap, tidyverse)
```
## Data Import and Preparation
```{r}
network <- st_read(dsn="data/geospatial", 
                   layer="Punggol_St")
childcare <- st_read(dsn="data/geospatial",
                     layer="Punggol_CC")
childcare_01 <-st_zm(childcare,drop = TRUE,
        what = "ZM")
```
## Visualising the Geospatial Data
```{r}

plot(st_geometry(network))
plot(childcare,add=T,col='red',pch = 19)
```

```{r}
tmap_mode("view")
tm_shape(childcare)+
  tm_dots(col ="red")+
tm_shape(network)+
  tm_lines()
tmap_mode('plot')
```
##Preparing the lixels objects
```{r}
lixels <- lixelize_lines(network, 
                         700, 
                         mindist = 350)
samples <- lines_center(lixels) 
```
```{r}
tmap_mode('view')
tm_shape(lixels) +
  tm_lines(col = 'blue') +
  tm_shape(samples) +
  tm_dots() 
tmap_mode('plot')
```
```{r}
#| eval: false

# Performing NKDE
densities <- nkde(network, 
                  events = childcare,  # Ensure childcare is an 'sf' object
                  w = rep(1, nrow(childcare)),  # Weights corresponding to each point in childcare
                  samples = samples,  # Centers of lixels as samples
                  kernel_name = "quartic",
                  bw = 350, 
                  div = "bw",
                  method = "simple", )
```
## visualising NKDE
```{r}
#| eval: false

samples$density <- densities
lixels$density <- densities

tmap_mode('view')
tm_shape(lixels)+
  tm_lines(col="density")+
tm_shape(childcare)+
  tm_dots()
tmap_mode('plot')
```
```{r}
kfun_childcare <- kfunctions(network, 
                             childcare,
                             start = 0, 
                             end = 1000, 
                             step = 50, 
                             width = 50, 
                             nsim = 50, 
                             resolution = 50,
                             verbose = FALSE, 
                             conf_int = 0.05)
kfun_childcare$plotk
```




