---
title: "Hands-on_Ex02"
author: "Luo Yuming"
date: "Sep 02 2024"
date-modified: "last-modified"
execute: 
  eval: true
  echo: true
  message: false
  freeze: true
---

------------------------------------------------------------------------
##Issue 1: Installing maptools
#the code chunk as shown below in order to avoid maptools being download and install repetitively every time the Quarto document been rendered.
```{r}
#| eval: false
install.packages("maptools",
                 repos = "https://packagemanager.posit.co/cran/2023-10-13")
```
```{r}
pacman::p_load(sf, raster, spatstat, tmap, tidyverse)
```
##Issue 2: Creating coastal outline
#in sf. package, there are two functions allow us to combine multiple simple features.
```{r}
mpsz_sf <- st_read(dsn = "data", layer = "MP14_SUBZONE_WEB_PL")
sg_sf <- mpsz_sf %>%
  st_union()
plot(sg_sf)
```
```{r}
#| eval: false
rdacc_sf <- read_csv("data/thai_road_accident_2019_2022.csv") %>%
  filter(!is.na (longitude) & longitude != "",
        !is.na(latitude) & latitude != "") %>%
  st_as_sf (coords = c(
    "longitude", "latitude"), 
     crs=4326) %>%
  st_transform(crs = 32647)
```

