---
title: "In-class_Ex04"
author: "Luo Yuming"
date: "Sep 16 2024"
date-modified: "last-modified"
execute: 
  eval: true
  echo: true
  message: false
  freeze: true
---

------------------------------------------------------------------------
```{r}
pacman::p_load(sf, spdep, tmap, tidyverse, knitr, ggstatsplot, GWmodel)   
```
## Data Import and Preparation
```{r}
hunan_sf <- st_read(dsn = "data/geospatial", 
                 layer = "Hunan")
hunan2012 <- read_csv("data/aspatial/Hunan_2012.csv")
hunan <- left_join(hunan_sf,hunan2012)%>%
  select(1:3, 7, 15, 16, 31, 32)
```
#Visualising Regional Development Indicator
```{r}
basemap <- tm_shape(hunan) +
  tm_polygons() +
  tm_text("NAME_3", size=0.5)

gdppc <- qtm(hunan, "GDPPC")
tmap_arrange(basemap, gdppc, asp=1, ncol=2)
```

#converting to spatialpolygonDataFrame
```{r}
hunan_sp <- hunan%>%
  as_Spatial()
```

#Determine adaptive bandwidth
```{r}
bw_CV <- bw.gwr(GDPPC ~ 1,
                data = hunan_sp,
                approach = "CV",
                adaptive = TRUE,
              kernel = "bisquare",
              longlat = T)
bw_CV
```
#computing geographically wieghted summary statistics
```{r}
gwstat <- gwss(data=hunan_sp,
               vars ="GDPPC",
               bw = bw_CV,
               kernel = "bisquare",
               adaptive=TRUE,
               longlat = T)
```
#preparing the output data
```{r}
gwstat_df <- as.data.frame(gwstat$SDF)
hunan_gstat <- cbind(hunan_sf, gwstat_df)
```

```{r}
tm_shape(hunan_gstat)+
  tm_fill("GDPPC_LM",
          n=5,
          style="quantile")+
  tm_borders(alpha = 0.5)+
  tm_layout(main.title = "Distribution of geographically weighted mean",
            main.title.position = "center",
            main.title.size = 1,
            legend.text.size = 0.8,
            legend.height = 1.50,
            legend.width = 1.50,
            frame= TRUE)
```
```{r}
 